# Valid values
valid_values:
  stages:
    - "0"
    - "1"
    - "1r"
    - "1c"
    - "2"
    - "3"
  cases:
    - uni
    - uni_switch
    - uniresp
    - switch
    - first
  ras:
    - ra1
    - ra2
    - both
  treatments:
    - imperfect
    - perfect
    - merged
  llms:
    - GPT_4O_0806
    - GPT_4O_1120
    - GPT_4O_MINI_0718
    - GPT_O1_1217
    - GPT_O1_MINI_0912
    - GPT_O3_MINI_0131
    - GROK_2_1212
    - CLAUDE_3_5_SONNET
    - CLAUDE_3_7_SONNET
    - GEMINI_2_FLASH
    - GEMINI_2_FLASH_LITE
    - GEMINI_1_5_PRO
    - NOVA_PRO_V1
    - MISTRAL_LARGE_2111
  llm_configs:
    - base
    - res1
    - res2
    - res3

# Default values to test models
defaults:
  llms: GPT_4O_1120
  llm_configs: base
  