# Base configurations for each LLM model
base:
  GPT_4O_0806:
    max_completion_tokens: 4096
    temperature: 0
    top_p: 1
    seed: 1240034
    frequency_penalty: 0
    presence_penalty: 0
  GPT_4O_1120:
    max_completion_tokens: 4096
    temperature: 0
    top_p: 1
    seed: 1240034
    frequency_penalty: 0
    presence_penalty: 0
  GPT_4O_MINI_0718:
    max_completion_tokens: 4096
    temperature: 0
    top_p: 1
    seed: 1240034
    frequency_penalty: 0
    presence_penalty: 0
  GPT_O1_1217:
    reasoning_effort: high
    max_completion_tokens: 4096
    seed: 1240034
  GPT_O1_MINI_0912:
    reasoning_effort: high
    max_completion_tokens: 4096
    seed: 1240034
  GROK_2_1212:
    max_completion_tokens: 4096
    temperature: 0
    top_p: 1
    seed: 1240034
    frequency_penalty: 0
    presence_penalty: 0
  GEMINI_1_5_PRO:
    max_output_tokens: 4096
    temperature: 0
    top_p: 1
    seed: 1240034
    frequency_penalty: 0
    presence_penalty: 0
  GEMINI_2_FLASH:
    max_output_tokens: 4096
    temperature: 0
    top_p: 1
    seed: 1240034
    frequency_penalty: 0
    presence_penalty: 0
  GEMINI_2_FLASH_LITE:
    max_output_tokens: 4096
    temperature: 0
    top_p: 1
    seed: 1240034
    frequency_penalty: 0
    presence_penalty: 0
  CLAUDE_3_5_SONNET:
    max_tokens: 4096
    temperature: 0
    top_p: 1
  CLAUDE_3_7_SONNET:
    max_tokens: 4096
    temperature: 0
    top_p: 1
  NOVA_PRO_V1:
    max_new_tokens: 4096
    temperature: 0
    top_p: 1
  MISTRAL_LARGE_2411:
    max_completion_tokens: 4096
    temperature: 0
    top_p: 1
    random_seed: 1240034
    frequency_penalty: 0
    presence_penalty: 0
  
# Res1 Configs
res1:
  GPT_4O_0806:
    max_completion_tokens: 4096
    temperature: 1
    top_p: 1
    seed: null
    frequency_penalty: 0
    presence_penalty: 0
  GPT_4O_1120:
    max_completion_tokens: 4096
    temperature: 1
    top_p: 1
    seed: null
    frequency_penalty: 0
    presence_penalty: 0
  GPT_4O_MINI_0718:
    max_completion_tokens: 4096
    temperature: 1
    top_p: 1
    seed: null
    frequency_penalty: 0
    presence_penalty: 0
  GPT_O1_1217:
    reasoning_effort: high
    max_completion_tokens: 4096
    seed: null
  GPT_O1_MINI_0912:
    reasoning_effort: high
    max_completion_tokens: 4096
    seed: null
  GROK_2_1212:
    max_completion_tokens: 4096
    temperature: 1
    top_p: 1
    seed: null
    frequency_penalty: 0
    presence_penalty: 0
  GEMINI_1_5_PRO:
    max_output_tokens: 4096
    temperature: 1
    top_p: 1
    seed: null
    frequency_penalty: 0
    presence_penalty: 0
  GEMINI_2_FLASH:
    max_output_tokens: 4096
    temperature: 1
    top_p: 1
    seed: null
    frequency_penalty: 0
    presence_penalty: 0
  GEMINI_2_FLASH_LITE:
    max_output_tokens: 4096
    temperature: 1
    top_p: 1
    seed: null
    frequency_penalty: 0
    presence_penalty: 0
  CLAUDE_3_5_SONNET:
    max_tokens: 4096
    temperature: 1
    top_p: 1
  CLAUDE_3_7_SONNET:
    max_tokens: 4096
    temperature: 1
    top_p: 1
  NOVA_PRO_V1:
    max_new_tokens: 4096
    temperature: 1
    top_p: 1
  MISTRAL_LARGE_2411:
    max_completion_tokens: 4096
    temperature: 1
    top_p: 1
    random_seed: null
    frequency_penalty: 0
    presence_penalty: 0

# Res2 Configs
res2:
  GPT_4O_0806:
    max_completion_tokens: 4096
    temperature: 0
    top_p: 1
    seed: null
    frequency_penalty: 0
    presence_penalty: 0
  GPT_4O_1120:
    max_completion_tokens: 4096
    temperature: 0
    top_p: 1
    seed: null
    frequency_penalty: 0
    presence_penalty: 0
  GPT_4O_MINI_0718:
    max_completion_tokens: 4096
    temperature: 0
    top_p: 1
    seed: null
    frequency_penalty: 0
    presence_penalty: 0
  GPT_O1_1217:
    reasoning_effort: high
    max_completion_tokens: 4096
    seed: null
  GPT_O1_MINI_0912:
    reasoning_effort: high
    max_completion_tokens: 4096
    seed: null
  GROK_2_1212:
    max_completion_tokens: 4096
    temperature: 0
    top_p: 1
    seed: null
    frequency_penalty: 0
    presence_penalty: 0
  GEMINI_1_5_PRO:
    max_output_tokens: 4096
    temperature: 0
    top_p: 1
    seed: null
    frequency_penalty: 0
    presence_penalty: 0
  GEMINI_2_FLASH:
    max_output_tokens: 4096
    temperature: 0
    top_p: 1
    seed: null
    frequency_penalty: 0
    presence_penalty: 0
  GEMINI_2_FLASH_LITE:
    max_output_tokens: 4096
    temperature: 0
    top_p: 1
    seed: null
    frequency_penalty: 0
    presence_penalty: 0
  CLAUDE_3_5_SONNET:
    max_tokens: 4096
    temperature: 0
    top_p: 1
  CLAUDE_3_7_SONNET:
    max_tokens: 4096
    temperature: 0
    top_p: 1
  NOVA_PRO_V1:
    max_new_tokens: 4096
    temperature: 0
    top_p: 1
  MISTRAL_LARGE_2411:
    max_completion_tokens: 4096
    temperature: 0
    top_p: 1
    random_seed: null
    frequency_penalty: 0
    presence_penalty: 0

# Res3 Configs
res3:
  GPT_4O_0806:
    max_completion_tokens: 4096
    temperature: 1
    top_p: 1
    seed: 1240034
    frequency_penalty: 0
    presence_penalty: 0
  GPT_4O_1120:
    max_completion_tokens: 4096
    temperature: 1
    top_p: 1
    seed: 1240034
    frequency_penalty: 0
    presence_penalty: 0
  GPT_4O_MINI_0718:
    max_completion_tokens: 4096
    temperature: 1
    top_p: 1
    seed: 1240034
    frequency_penalty: 0
    presence_penalty: 0
  GPT_O1_1217:
    reasoning_effort: high
    max_completion_tokens: 4096
    seed: 1240034
  GPT_O1_MINI_0912:
    reasoning_effort: high
    max_completion_tokens: 4096
    seed: 1240034
  GROK_2_1212:
    max_completion_tokens: 4096
    temperature: 1
    top_p: 1
    seed: 1240034
    frequency_penalty: 0
    presence_penalty: 0
  GEMINI_1_5_PRO:
    max_output_tokens: 4096
    temperature: 1
    top_p: 1
    seed: 1240034
    frequency_penalty: 0
    presence_penalty: 0
  GEMINI_2_FLASH:
    max_output_tokens: 4096
    temperature: 1
    top_p: 1
    seed: 1240034
    frequency_penalty: 0
    presence_penalty: 0
  GEMINI_2_FLASH_LITE:
    max_output_tokens: 4096
    temperature: 1
    top_p: 1
    seed: 1240034
    frequency_penalty: 0
    presence_penalty: 0
  CLAUDE_3_5_SONNET:
    max_tokens: 4096
    temperature: 1
    top_p: 1
  CLAUDE_3_7_SONNET:
    max_tokens: 4096
    temperature: 1
    top_p: 1
  NOVA_PRO_V1:
    max_new_tokens: 4096
    temperature: 1
    top_p: 1
  MISTRAL_LARGE_2411:
    max_completion_tokens: 4096
    temperature: 1
    top_p: 1
    random_seed: 1240034
    frequency_penalty: 0
    presence_penalty: 0